# A/B-тест нового алгоритма в приложении для онлайн-знакомств

## Описание задачи

Вы работаете аналитиком в приложении для онлайн-знакомств.

Механика приложения устроена следующим образом:

* пользователи видят анкеты друг друга;
* пользователь может поставить анкете **лайк** или **дизлайк**;
* если два пользователя взаимно поставили друг другу лайк, происходит **мэтч**;
* после мэтча у пользователей появляется возможность познакомиться.

## Эксперимент

Команда приложения разработала новый алгоритм подбора наиболее подходящих анкет.

Чтобы проверить эффективность нового алгоритма, был проведён A/B-тест. Все пользователи были разделены на две группы:

* **Группа 0** — пользователи со старым алгоритмом подбора анкет;
* **Группа 1** — пользователи с новым алгоритмом подбора анкет.

## Данные

В данных содержится выгрузка логов взаимодействий пользователей друг с другом.

Для каждой пары пользователей указаны:

* группа в A/B-тесте;
* факт мэтча между пользователями.

## Задача аналитика

Необходимо оценить, действительно ли новый алгоритм улучшил качество сервиса.

Для этого нужно:

1. выбрать метрики, которые отражают качество работы сервиса;
2. рассчитать эти метрики для двух групп;
3. статистически сравнить значения метрик между группами;
4. сделать вывод о влиянии нового алгоритма.

## Итоговый результат

Результатом работы должно быть аналитическое заключение с ответом на вопрос:

**Стоит ли включать новую систему поиска анкет на всех пользователей?**

## Кейс 1
Чему равна средняя доля мэтчей на пользователя в 0 группе? Ответ нужно предоставить до 4-х знаков после запятой без округлений.

In [1]:
import pandas as pd

In [2]:
dating_data = pd.read_csv('dating_data.csv')

In [3]:
dating_data.head()

   user_id_1  user_id_2  group  is_match
0         79         91      1         1
1        716        353      1         1
2        423        677      0         0
3        658        165      1         1
4        969        155      0         1

In [33]:
average_share_0 = dating_data.query('group == 0').groupby('user_id_1').is_match.mean().round(2).mean()
average_share_0

np.float64(0.1935928143712575)

## Кейс 2
Чему равна средняя доля мэтчей на пользователя в 1 группе? Ответ нужно предоставить до 4-х знаков после запятой без округлений.

In [35]:
average_share_1 = dating_data.query('group == 1').groupby('user_id_1').is_match.mean().round(2).mean()
average_share_1

np.float64(0.4024048096192385)

## Кейс 3
Проверьте, есть ли различия в средней доле мэтчей на пользователя в двух полученных группах.

In [66]:
test = dating_data.query('group == 1').groupby('user_id_1', as_index=False).agg(match_share=('is_match', 'mean')).match_share.round(2)
control = dating_data.query('group == 0').groupby('user_id_1', as_index=False).agg(match_share=('is_match', 'mean')).match_share.round(2)

In [70]:
import scipy.stats as st

st.ttest_ind(control, test, equal_var=False)

TtestResult(statistic=np.float64(-26.481431782585016), pvalue=np.float64(7.890669157070396e-117), df=np.float64(973.9371185920583))

Для проверки гипотезы я использую T-КРИТЕРИЙ УЭЛЧА,
поскольку переменные обе — КОЛИЧЕСТВЕННЫЕ.
Нулевая гипотеза ОТКЛОНЯЕТСЯ,
поскольку p-value МЕНЬШЕ 0.05.

## Кейс 4
Каково значение t-статистики для проверки гипотезы о различии долей мэтчей? Ответ нужно предоставить до 4-х знаков после запятой без округлений.

In [71]:
-26.4814

-26.4814

## Кейс 5
Проверьте, есть ли различия в среднем количестве действий на пользователя в двух полученных группах. Чему равно значение среднего количества действий в 0 группе? Ответ нужно предоставить до 4-х знаков после запятой без округлений.

In [72]:
dating_data.head()

   user_id_1  user_id_2  group  is_match
0         79         91      1         1
1        716        353      1         1
2        423        677      0         0
3        658        165      1         1
4        969        155      0         1

In [76]:
avg_move_0 =  dating_data.query('group == 0').groupby('user_id_1').is_match.count().mean()
avg_move_0

np.float64(9.564870259481038)

## Кейс 7
Чему равно значение среднего количества действий в 1 группе? Ответ нужно предоставить до 4-х знаков после запятой без округлений.

In [77]:
avg_move_1 =  dating_data.query('group == 1').groupby('user_id_1').is_match.count().mean()
avg_move_1

np.float64(19.482965931863728)

## Кейс 8
Для проверки гипотезы я использую T-КРИТЕРИЙ, поскольку переменные обе — КОЛИЧЕСТВЕННЫЕ. Нулевая гипотеза ОТКЛОНЯЕТСЯ, поскольку p-value МЕНЬШЕ 0.05.

## Кейс 9
Каково значение t-статистики для проверки гипотезы о различиях в среднем количестве действий?

In [89]:
testing = testing = dating_data.query('group == 1').groupby('user_id_1').agg( count_1 = ( 'is_match' ,'count')).count_1
controling = dating_data.query('group == 0').groupby('user_id_1').agg( count_0 = ( 'is_match' ,'count')).count_0

In [90]:
st.ttest_ind(controling, testing)

TtestResult(statistic=np.float64(-51.85383774946492), pvalue=np.float64(1.89428770640453e-285), df=np.float64(998.0))

In [91]:
-51.8538

-51.8538

## Кейс 10
Стоит ли включать новую систему поиска анкет на всех пользователей?

Да, потому что новая система увеличивает метрики.
 Результаты A/B-теста показали, что новая система улучшила долю мэтчей и активность клиентов в продукте.